# ---------------------------------------------------------------------------- #
#                                 CI OVERVIEW                                  #
#                                 ~~~~~~~~~~~                                  #
#                                                                              #
#  1) The following scripts should be preserved in `package.json`:             #
#                                                                              #
#        lint -- Run a linter against source files.                            #
#       build -- Build CJS and UMD bundles for the module.                     #
#        test -- Run unit tests and build a coverage report using              #
#                Istanbul/`nyc`.                                               #
#     release -- Publishes all unrelease packages to NPM.                      #
#                                                                              #
#                                                                              #
#  2) Ensure the aliases for `&dependency-paths` and `&build-output-paths`     #
#     below properly reflect the dependency and output directories             #
#     of the module.                                                           #
#                                                                              #
# ---------------------------------------------------------------------------- #

version: 2.1

# --- YAML Aliases ----------------------------------------------------------- #

aliases: [
  # List of dependency paths that should be persisted to the
  # CircleCI workspace.
  &dependency-paths [
    "node_modules",
    "packages/provider/node_modules",
    "packages/react-native/node_modules",
    "packages/types/node_modules",
    "packages/web/node_modules"
  ],

  # List of build output paths that should be persisted to the
  # CircleCI workspace.
  &build-output-paths [
    "packages/provider/dist",
    "packages/react-native/dist",
    "packages/types/dist",
    "packages/web/dist"
  ],

  # NPM lockfile cache key (update "vN" => "vN+1" to cache-bust).
  &dependency-cache-key "v2-dependency-cache-{{ checksum \"yarn.lock\" }}",

  &workspace-root "/home/circleci/project",

  &attach-workspace {
    attach_workspace: {
      at: *workspace-root
    }
  },

  # Filter pull requests not in "master" or "next" (development code)
  &filter-default-branches {
    filters: {
      branches: {
        ignore: "/^master$|^next$/"
      }
    }
  },

  # Filter pull requests in "master" only (production code).
  &filter-release-branches-only {
    filters: {
      branches: {
        only: [
          "master",
          "next",
        ]
      }
    }
  },
]

# --- Executor definitions --------------------------------------------------- #

executors:
  default:
    docker:
      - image: circleci/node:10-browsers

# --- Job definitions -------------------------------------------------------- #

jobs:
  # Installs Node dependencies via NPM, caches them, then persists
  # to the workspace.
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          key: *dependency-cache-key
      - run:
          name: Install Module Dependencies
          command: yarn install
      - save_cache:
          paths: *dependency-paths
          key: *dependency-cache-key
      - persist_to_workspace:
          paths: *dependency-paths
          root: *workspace-root

  # Runs a linter against relevant source files.
  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint source files
          command: yarn run lint

  # Builds modules and persists the build output to the workspace.
  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Bump version
          command: lerna version $(auto version) --no-git-tag-version
      - run:
          name: Build modules
          command: yarn run build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  # Run unit tests and builds a coverage report.
  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run unit tests
          command: yarn run test
      # For display in CircleCI Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: packages/provider/coverage
      - store_artifacts:
          path: packages/react-native/coverage
      - store_artifacts:
          path: packages/web/coverage

  create-release:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Publish to NPM
          command: yarn run release

# --- Workflow definitions --------------------------------------------------- #

workflows:
  # Builds modules, verifies code with the linter, runs unit tests, and builds a
  # coverage report.
  pull-request:
    jobs:
      - install-dependencies: *filter-default-branches

      - build:
          requires:
            - install-dependencies

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

  # Builds modules, verifies code with the linter, runs unit tests, and
  # publishes the built packages to NPM.
  publish-to-npm:
    jobs:
      - install-dependencies: *filter-release-branches-only

      - build:
          requires:
            - install-dependencies

      - test:
          requires:
            - build

      - lint:
          requires:
            - build

        # Manual approval step as a final gatekeeper to prevent
        # possible mistakes!
      - confirm-release:
          type: approval
          requires:
            - test
            - lint

      - create-release:
          requires:
            - confirm-release
            - test
            - lint
