version: 2.1

# --- YAML Aliases ----------------------------------------------------------- #

aliases: [
  # List of dependency paths that should be persisted to the
  # CircleCI workspace.
  &dependency-paths [
    "node_modules",
    "packages/@magic-ext/*/node_modules",
    "packages/@magic-sdk/*/node_modules",
    "packages/*/node_modules",
  ],

  # List of Yarn cache paths that should be persisted to the
  # CircleCI workspace cache.
  &yarn-cache-paths [
    ".yarn/cache",
    ".yarn/unplugged",
  ],

  # List of build output paths that should be persisted to the
  # CircleCI workspace.
  &build-output-paths [
    "packages/@magic-ext/*/dist",
    "packages/@magic-sdk/*/dist",
    "packages/*/dist",
  ],

  # Yarn lockfile cache key (update "vN" => "vN+1" to cache-bust).
  &dependency-cache-key "v3-dependency-cache-{{ checksum \"yarn.lock\" }}",

  &workspace-root "/home/circleci/project",

  &attach-workspace {
    attach_workspace: {
      at: *workspace-root
    }
  },

  # --- Filters --- #

  # Filter pull requests not in "master" or "next" (development code).
  # Filters ONLY NON-FORKED branches.
  &filter-default-branches {
    filters: {
      branches: {
        # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
        ignore: "/^master$|^next$|pull\\/[0-9]+/"
      }
    }
  },

  # Filter pull requests not in "master" or "next" (development code).
  # Filter ONLY FORKED branches.
  &filter-forked-default-branches {
    filters: {
      branches: {
        # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
        only: "/pull\\/[0-9]+/"
      }
    }
  },

  # Filter pull requests in "master" or "next" only (production code).
  &filter-release-branches-only {
    filters: {
      branches: {
        only: [
          "master",
          "next",
          "early-release"
        ]
      }
    }
  },
]

# --- Executor definitions --------------------------------------------------- #

executors:
  default:
    docker:
      - image: circleci/node:14.17.0-browsers
    resource_class: medium

# --- Job definitions -------------------------------------------------------- #

jobs:
  # Installs Node dependencies via NPM, caches them, then persists
  # to the workspace.
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          key: *dependency-cache-key
      - run:
          name: Install Module Dependencies
          command: yarn install
      - save_cache:
          paths: *yarn-cache-paths
          key: *dependency-cache-key
      - persist_to_workspace:
          paths: *dependency-paths
          root: *workspace-root

  # Runs a linter against relevant source files.
  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint source files
          command: yarn run lint

  # Builds modules and persists the build output to the workspace (non-forked branches only).
  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Apply semver updates (if any)
          command: |
            AUTO_VERSION=$(yarn auto version)
            if [[ $AUTO_VERSION == pre* ]]; then
              yarn lerna version $(echo $AUTO_VERSION) --no-git-tag-version --no-push --yes --preid $(echo $CIRCLE_BRANCH)
            elif [[ $AUTO_VERSION ]]; then
              yarn lerna version $(echo $AUTO_VERSION) --no-git-tag-version --no-push --yes
            fi

      - run:
          name: Build modules
          command: yarn run build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  # Builds modules and persists the build output to the workspace (forked branches only).
  build-fork:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn run build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  # Run unit tests and builds a coverage report.
  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run unit tests
          command: yarn run test
      # For display in CircleCI Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: packages/@magic-sdk/provider/coverage
      - store_artifacts:
          path: packages/@magic-sdk/react-native/coverage
      - store_artifacts:
          path: packages/magic-sdk/coverage

  # Publish all packages to NPM
  create-release:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Publish to NPM
          command: yarn auto shipit

# --- Workflow definitions --------------------------------------------------- #

workflows:
  # Builds modules, verifies code with the linter, runs unit tests, and builds a
  # coverage report (non-forked branches only).
  pull-request:
    jobs:
      - install-dependencies: *filter-default-branches

      - build:
          requires:
            - install-dependencies

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

  # Builds modules, verifies code with the linter, runs unit tests, and builds a
  # coverage report (forked branches only).
  forked-pull-request:
    jobs:
      - install-dependencies: *filter-forked-default-branches

      - build-fork:
          requires:
            - install-dependencies

      - lint:
          requires:
            - build-fork

      - test:
          requires:
            - build-fork

  # Builds modules, verifies code with the linter, runs unit tests, and
  # publishes the built packages to NPM.
  publish-to-npm:
    jobs:
      - install-dependencies

      - build:
          requires:
            - install-dependencies

      - test:
          requires:
            - build

      - lint:
          requires:
            - build

        # Manual approval step as a final gatekeeper to prevent
        # possible mistakes!
      - confirm-release:
          type: approval
          requires:
            - test
            - lint

      - create-release:
          requires:
            - confirm-release
            - test
            - lint
